// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: coroot/service/v1/rpc.proto

package v1

import (
	v1 "github.com/coroot/coroot/api/proto/coroot/event/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventServiceUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spans []*v1.ServerSpan `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
}

func (x *EventServiceUploadRequest) Reset() {
	*x = EventServiceUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coroot_service_v1_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventServiceUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventServiceUploadRequest) ProtoMessage() {}

func (x *EventServiceUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coroot_service_v1_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventServiceUploadRequest.ProtoReflect.Descriptor instead.
func (*EventServiceUploadRequest) Descriptor() ([]byte, []int) {
	return file_coroot_service_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *EventServiceUploadRequest) GetSpans() []*v1.ServerSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

type EventServiceUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventServiceUploadResponse) Reset() {
	*x = EventServiceUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coroot_service_v1_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventServiceUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventServiceUploadResponse) ProtoMessage() {}

func (x *EventServiceUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coroot_service_v1_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventServiceUploadResponse.ProtoReflect.Descriptor instead.
func (*EventServiceUploadResponse) Descriptor() ([]byte, []int) {
	return file_coroot_service_v1_rpc_proto_rawDescGZIP(), []int{1}
}

var File_coroot_service_v1_rpc_proto protoreflect.FileDescriptor

var file_coroot_service_v1_rpc_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63,
	0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x1a, 0x21, 0x63, 0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x19, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x63, 0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x05, 0x73, 0x70,
	0x61, 0x6e, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x77, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x67, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2c, 0x2e, 0x63, 0x6f,
	0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x63, 0x6f, 0x72, 0x6f,
	0x6f, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2f,
	0x63, 0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coroot_service_v1_rpc_proto_rawDescOnce sync.Once
	file_coroot_service_v1_rpc_proto_rawDescData = file_coroot_service_v1_rpc_proto_rawDesc
)

func file_coroot_service_v1_rpc_proto_rawDescGZIP() []byte {
	file_coroot_service_v1_rpc_proto_rawDescOnce.Do(func() {
		file_coroot_service_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_coroot_service_v1_rpc_proto_rawDescData)
	})
	return file_coroot_service_v1_rpc_proto_rawDescData
}

var file_coroot_service_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coroot_service_v1_rpc_proto_goTypes = []any{
	(*EventServiceUploadRequest)(nil),  // 0: coroot.service.v1.EventServiceUploadRequest
	(*EventServiceUploadResponse)(nil), // 1: coroot.service.v1.EventServiceUploadResponse
	(*v1.ServerSpan)(nil),              // 2: coroot.event.v1.ServerSpan
}
var file_coroot_service_v1_rpc_proto_depIdxs = []int32{
	2, // 0: coroot.service.v1.EventServiceUploadRequest.spans:type_name -> coroot.event.v1.ServerSpan
	0, // 1: coroot.service.v1.EventService.Upload:input_type -> coroot.service.v1.EventServiceUploadRequest
	1, // 2: coroot.service.v1.EventService.Upload:output_type -> coroot.service.v1.EventServiceUploadResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coroot_service_v1_rpc_proto_init() }
func file_coroot_service_v1_rpc_proto_init() {
	if File_coroot_service_v1_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coroot_service_v1_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EventServiceUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coroot_service_v1_rpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EventServiceUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coroot_service_v1_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coroot_service_v1_rpc_proto_goTypes,
		DependencyIndexes: file_coroot_service_v1_rpc_proto_depIdxs,
		MessageInfos:      file_coroot_service_v1_rpc_proto_msgTypes,
	}.Build()
	File_coroot_service_v1_rpc_proto = out.File
	file_coroot_service_v1_rpc_proto_rawDesc = nil
	file_coroot_service_v1_rpc_proto_goTypes = nil
	file_coroot_service_v1_rpc_proto_depIdxs = nil
}
