version: '3.8'

name: localhost

services:
  coroot:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/obser/coroot:latest
    volumes:
      - /D/tmp/coroot/coroot_data:/data
    ports:
      - "8888:8888"  # This port is used as: Web UI, OTel collector.
      - "40000:40000" # For DLV
    command:
      - '--data-dir=/data'
      - '--bootstrap-prometheus-url=http://prometheus:9090'
      - '--bootstrap-refresh-interval=15s'
      - '--bootstrap-clickhouse-address=clickhouse:9000'
    depends_on:
      - clickhouse
      - prometheus

  node-agent:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/obser/coroot-node-agent:latest
    privileged: true
    pid: "host"
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/host/sys/fs/cgroup
      - /D/tmp/coroot/node_agent_data:/data
    command:
      - '--collector-endpoint=http://coroot:8888'
      - '--clickhouse-endpoint=clickhouse:9000'
      - '--cgroupfs-root=/host/sys/fs/cgroup'
      - '--wal-dir=/data'
    depends_on:
      - clickhouse
      - coroot

  cluster-agent:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/obser/coroot-cluster-agent:latest
    volumes:
      - /D/tmp/coroot/cluster_agent_data:/data
    command:
      - '--coroot-url=http://coroot:8888'
      - '--metrics-scrape-interval=15s'
      - '--metrics-wal-dir=/data'
    depends_on:
      - coroot

  coroot-tracing-algo:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/obser/coroot-tracing-algo:latest
    environment:
      COROOT_CLICKHOUSE_ADDRESS: "clickhouse:8123"
    ports:
      - "4200:4200"
    depends_on:
      - clickhouse

  prometheus:
    restart: always
    image: prom/prometheus:v2.45.4
    volumes:
      - /D/tmp/coroot/prometheus_data:/prometheus  # chmod 777 -R
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    ports:
      - "9090:9090"

  clickhouse:
    restart: always
    image: clickhouse/clickhouse-server:24.3
    volumes:
      - /D/tmp/coroot/clickhouse_data:/var/lib/clickhouse
      - /D/tmp/coroot/clickhouse_logs:/var/log/clickhouse-server
    ports:
      - "9000:9000"
      - "8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # 以下为被测应用负载。
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "16686:16686"

  redis:
    image: registry.cn-beijing.aliyuncs.com/obser/redis:4.0.9
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "6379:6379"

  foo-svc:
    image: registry.cn-beijing.aliyuncs.com/obser/foo-svc:0.1.0
    environment:
      JAEGER_UDP_SENDER_HOST: jaeger
    ports:
      - "8080:8080"
    links:
      - redis
      - jaeger

  bar-svc:
    image: registry.cn-beijing.aliyuncs.com/obser/bar-svc:0.1.0
    environment:
      JAEGER_UDP_SENDER_HOST: jaeger
    links:
      - redis
      - jaeger

  loo-svc:
    image: registry.cn-beijing.aliyuncs.com/obser/loo-svc:0.1.0
    environment:
      JAEGER_UDP_SENDER_HOST: jaeger
    links:
      - redis
      - jaeger
