version: '3.8'

name: coroot-local

volumes:
  prometheus_data: { }
  clickhouse_data: { }
  clickhouse_logs: { }
  coroot_data: { }
  node_agent_data: { }
  cluster_agent_data: { }

services:
  coroot:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/obser/coroot:latest
    volumes:
      - /tmp/coroot_data:/data
    ports:
      - '127.0.0.1:8888:8888'  # This port is used as: Web UI, OTel collector.
    command:
      - '--data-dir=/data'
      - '--bootstrap-prometheus-url=http://prometheus:9090'
      - '--bootstrap-refresh-interval=15s'
      - '--bootstrap-clickhouse-address=clickhouse:9000'
    depends_on:
      - clickhouse
      - prometheus

  coroot-node-agent:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/obser/coroot-node-agent:latest
    privileged: true
    pid: "host"
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/host/sys/fs/cgroup
      - /tmp/coroot_node_agent_data:/data
    command:
      - '--collector-endpoint=http://coroot:8888'
      - '--clickhouse-endpoint=clickhouse:9000'
      - '--cgroupfs-root=/host/sys/fs/cgroup'
      - '--wal-dir=/data'
    depends_on:
      - clickhouse

  prometheus:
    restart: always
    image: prom/prometheus:v2.45.4
    volumes:
      # First run `chmod 777 -R /tmp/coroot_*` to prepare the disk.
      - /tmp/coroot_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    ports:
      - '127.0.0.1:9090:9090'

  clickhouse:
    restart: always
    image: clickhouse/clickhouse-server:24.3
    volumes:
      - /tmp/coroot_clickhouse_data:/var/lib/clickhouse
      - /tmp/coroot_clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse-server-config.xml:/etc/clickhouse-server/config.xml
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:8123:8123'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # 以下为被测应用。
  redis:
    image: bitnami/redis:4.0.9
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - 16686:16686

  foo-svc:
    image: chanjarster/spring-boot-istio-jaeger-demo-foo-svc:0.1.0
    environment:
      JAEGER_UDP_SENDER_HOST: jaeger
    ports:
      - 8080:8080
    links:
      - bar-svc
      - redis
      - jaeger

  bar-svc:
    image: chanjarster/spring-boot-istio-jaeger-demo-bar-svc:0.1.0
    environment:
      JAEGER_UDP_SENDER_HOST: jaeger
    links:
      - loo-svc
      - redis
      - jaeger

  loo-svc:
    image: chanjarster/spring-boot-istio-jaeger-demo-loo-svc:0.1.0
    environment:
      JAEGER_UDP_SENDER_HOST: jaeger
    links:
      - redis
      - jaeger
