version: '3.8'

name: coroot-local

volumes:
  prometheus_data: { }
  clickhouse_data: { }
  clickhouse_logs: { }
  coroot_data: { }
  node_agent_data: { }
  cluster_agent_data: { }

services:
  coroot:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/obser/coroot:latest
    volumes:
      - /D/tmp/coroot/coroot_data:/data
    ports:
      - '127.0.0.1:8888:8888'  # This port is used as: Web UI, OTel collector.
    command:
      - '--data-dir=/data'
      - '--bootstrap-prometheus-url=http://prometheus:9090'
      - '--bootstrap-refresh-interval=15s'
      - '--bootstrap-clickhouse-address=clickhouse:9000'
    depends_on:
      - clickhouse
      - prometheus

  coroot-node-agent:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/obser/coroot-node-agent:latest
    privileged: true
    pid: "host"
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/host/sys/fs/cgroup
      - /D/tmp/coroot/node_agent_data:/data
    command:
      - '--collector-endpoint=http://coroot:8888'
      - '--clickhouse-endpoint=clickhouse:9000'
      - '--cgroupfs-root=/host/sys/fs/cgroup'
      - '--wal-dir=/data'
    depends_on:
      - clickhouse

  coroot-tracing-algo:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/obser/coroot-tracing-algo:latest
    ports:
      - '127.0.0.1:4200:4200'
    depends_on:
      - clickhouse

  prometheus:
    restart: always
    image: prom/prometheus:v2.45.4
    volumes:
      # Firstly `chmod 777 -R /D/tmp/coroot/clickhouse_data`
      - /D/tmp/coroot/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    ports:
      - '127.0.0.1:9090:9090'

  clickhouse:
    restart: always
    image: clickhouse/clickhouse-server:24.3
    volumes:
      - /D/tmp/coroot/clickhouse_data:/var/lib/clickhouse
      - /D/tmp/coroot/clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse-server-config.xml:/etc/clickhouse-server/config.xml
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:8123:8123'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
